### ISSUE TITLE
(Questions) Curious about development

### ISSUE THREAD

**Issue by PhweeDev** [Team-Remastered/BetterEnd-Forge#1]
Hello, I hope I'm not disturbing anything. I saw this repo out of sheer curiosity. I'm excited to see BetterEnd Forge continue to move toward modern versions. I had a few questions and I hope you don't mind answering.

1. After you complete this, do you plan to release it on CF/Modrinth?
2. After the 1,18.2 version is done, do you plan on porting to 1.19.2?
3. Do you plan on porting Better Nether Reforged as well?

Thank you for your time,
Phwee

**Comment by Jack-Bagel** [comment]
Hi, we're happy that you find interest in our development, to answer your questions,

We do plan on releasing the mod once it's completed but we will contact the dev of BetterEnd beforehand to make sure it's okay with them. As for the 1.19.2 port, we didn't plan that far into the future but if everything goes well maybe. Finally, we don't plan on porting BetterNether to forge.

Don't hesitate to ask any other questions you have!

**Comment by PhweeDev** [comment]
Ahh cool, thanks for responding! I'm interesting in seeing how far this mod port goes in the future. I'll certainly be keeping an eye on this!
