### ISSUE TITLE
Issue while building the mod

### ISSUE THREAD

**Issue by zorago** [Team-Remastered/BetterEnd-Forge#2]
Here is the following error, hope you can fix it.

Eitherway do you have a idea for when you will be ready to release the mod ? Or is current state ?

> Configure project :
MixinGradle did not locate the diffplug APT plugin, skipping eclipse task configuration
Java: 17.0.8 JVM: 17.0.8+9-LTS-211(Oracle Corporation) Arch: amd64

> Task :compileJava FAILED
D:\TÚlÚchargement\BetterEnd-Forge-main\src\main\java\ru\betterend\bclib\blocks\BaseLeavesBlock.java:47: error: ')' expected
            .blockVision((state, world, pos) -> false);
                                                      ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
4 actionable tasks: 4 executed

**Comment by zorago** [comment]
![image](https://github.com/Team-Remastered/BetterEnd-Forge/assets/151692999/0818bab5-5ac3-4d90-bd68-70648eb36a65)

**Comment by Jack-Bagel** [comment]
Yeah the port is not ready yet and we do not have a release date atm unfortunatly.
